import { prisma } from "@/lib/prisma";
import { getVolunteerDashboard } from "./volunteer";

export async function generateCv(userId: string) {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw new Error("User not found");

  const dashboard = await getVolunteerDashboard(userId);
  const skills = dashboard.skills.map((s) => `${s.name} (${s.value}/100)`).join(", ");

  const experience = dashboard.timeline
    .map((t) => `• ${t.title} — ${t.org} (${t.date}, ${t.hours}h verified)`)
    .join("\n");

  const certs = dashboard.certificates.map((c) => `• ${c.name} (${c.issuer})`).join("\n");

  const content = `${user.name.toUpperCase()}
Volunteer · Social Capital Passport
Email: ${user.email}

PROFILE SUMMARY
Verified volunteer with ${dashboard.stats.impactHours} impact hours, Trust Score ${dashboard.stats.trustScore}/100, and Admissions Readiness ${dashboard.stats.admissionsReadiness}%. Demonstrated leadership (index ${dashboard.stats.leadershipIndex}) across international-ready service experiences.

CORE SKILLS
${skills || "Leadership, Communication, Teamwork"}

VERIFIED EXPERIENCE
${experience || "• No verified entries yet — apply to opportunities to build your portfolio."}

CERTIFICATIONS
${certs || "• Certificates will appear as you complete verified events."}

Generated by Qamqor AI Admissions Suite · ${new Date().toLocaleDateString()}`;

  await prisma.aiGeneration.create({ data: { userId, type: "CV", content } });
  return { content };
}

export async function generateMotivationLetter(userId: string, program = "a leading international university program") {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw new Error("User not found");

  const dashboard = await getVolunteerDashboard(userId);
  const highlight = dashboard.timeline[0];

  const content = `Dear Admissions Committee,

My name is ${user.name}, and I am writing to express my strong interest in ${program}. Through verified volunteer work on the Qamqor platform, I have built a portfolio of real-world impact that reflects both commitment and measurable leadership.

With ${dashboard.stats.impactHours} verified impact hours and a Trust Score of ${dashboard.stats.trustScore}, my experience is validated by partner organizations — not self-reported. ${
    highlight
      ? `Most recently, I contributed to ${highlight.title} with ${highlight.org}, completing ${highlight.hours} verified hours.`
      : "I am actively expanding my verified service portfolio through curated opportunities."
  }

My admissions readiness score of ${dashboard.stats.admissionsReadiness}% reflects consistent growth in skills including ${dashboard.skills
    .slice(0, 3)
    .map((s) => s.name)
    .join(", ") || "leadership and collaboration"}. I am eager to bring this verified social capital — and the empathy, discipline, and global perspective it represents — to your academic community.

Thank you for your consideration.

Sincerely,
${user.name}

Generated by Qamqor AI · ${new Date().toLocaleDateString()}`;

  await prisma.aiGeneration.create({ data: { userId, type: "MOTIVATION", content } });
  return { content };
}
