import { prisma } from "@/lib/prisma";
import { getVolunteerDashboard } from "./volunteer";

const EMPTY_DASHBOARD = {
  stats: { trustScore: 0, leadershipIndex: 0, impactHours: 0, admissionsReadiness: 0 },
  timeline: [] as { title: string; org: string; date: string; hours: number }[],
  skills: [] as { name: string; value: number }[],
  certificates: [] as { name: string; issuer: string }[],
};

async function persistGeneration(userId: string, type: string, content: string) {
  try {
    await prisma.aiGeneration.create({ data: { userId, type, content } });
  } catch (err) {
    console.error(`[AI] Could not save ${type} generation (table may be missing)`, err);
  }
}

export async function generateCv(userId: string) {
  let userName = "Volunteer";
  let userEmail = "";
  let dashboard = EMPTY_DASHBOARD;

  try {
    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) throw new Error("User not found");
    userName = user.name;
    userEmail = user.email;
    dashboard = await getVolunteerDashboard(userId);
  } catch (err) {
    console.error("[AI] CV: partial data load failed, using defaults", err);
    if (err instanceof Error && err.message === "User not found") {
      throw err;
    }
  }

  const skills = dashboard.skills.map((s) => `${s.name} (${s.value}/100)`).join(", ");
  const experience = dashboard.timeline
    .map((t) => `• ${t.title} — ${t.org} (${t.date}, ${t.hours}h verified)`)
    .join("\n");
  const certs = dashboard.certificates.map((c) => `• ${c.name} (${c.issuer})`).join("\n");

  const content = `${userName.toUpperCase()}
Volunteer · Social Capital Passport
Email: ${userEmail || "—"}

PROFILE SUMMARY
Generated CV based on volunteer data. Verified volunteer with ${dashboard.stats.impactHours} impact hours, Trust Score ${dashboard.stats.trustScore}/100, and Admissions Readiness ${dashboard.stats.admissionsReadiness}%.

CORE SKILLS
${skills || "Leadership, Communication, Teamwork"}

VERIFIED EXPERIENCE
${experience || "• No verified entries yet — apply to opportunities to build your portfolio."}

CERTIFICATIONS
${certs || "• Certificates will appear as you complete verified events."}

Generated by Qamqor AI Admissions Suite · ${new Date().toLocaleDateString()}`;

  await persistGeneration(userId, "CV", content);
  return { content, text: content };
}

export async function generateMotivationLetter(userId: string, program = "a leading international university program") {
  let userName = "Volunteer";
  let dashboard = EMPTY_DASHBOARD;

  try {
    const user = await prisma.user.findUnique({ where: { id: userId } });
    if (!user) throw new Error("User not found");
    userName = user.name;
    dashboard = await getVolunteerDashboard(userId);
  } catch (err) {
    console.error("[AI] Letter: partial data load failed, using defaults", err);
    if (err instanceof Error && err.message === "User not found") {
      throw err;
    }
  }

  const highlight = dashboard.timeline[0];
  const content = `Dear Admissions Committee,

My name is ${userName}, and I am writing to express my strong interest in ${program}. Through verified volunteer work on the Qamqor platform, I have built a portfolio of real-world impact that reflects both commitment and measurable leadership.

With ${dashboard.stats.impactHours} verified impact hours and a Trust Score of ${dashboard.stats.trustScore}, my experience is validated by partner organizations. ${
    highlight
      ? `Most recently, I contributed to ${highlight.title} with ${highlight.org}, completing ${highlight.hours} verified hours.`
      : "I am actively expanding my verified service portfolio through curated opportunities."
  }

My admissions readiness score of ${dashboard.stats.admissionsReadiness}% reflects consistent growth in skills including ${
    dashboard.skills
      .slice(0, 3)
      .map((s) => s.name)
      .join(", ") || "leadership and collaboration"
  }.

Thank you for your consideration.

Sincerely,
${userName}

Generated by Qamqor AI · ${new Date().toLocaleDateString()}`;

  await persistGeneration(userId, "MOTIVATION", content);
  return { content, text: content };
}
